### ISSUE TITLE
Include widgets for project assessment in the QM Attribute dashboard

### ISSUE THREAD

**Issue by acs** [Bitergia/prosoul#18]
Apart from showing the metrics included in an Attribute (evolution in time, and aggregated value), it is interesting that the assessment data is also present in the dashboard.

In this way, analyzing the dashoard will explain the assessment for a project with the data. The goal is to explain visually why the assessment results.

**Comment by acs** [comment]
http://www.balancedscorecard.org/portals/0/images/2017/kpi%20dashboard.jpg

In meditor case, the idea is to have 5 thresholds per metric, so the gauge will have 5 regions.

**Comment by dlumbrer** [comment]
Now, we have the Polar visualization (https://github.com/dlumbrer/kbn_polar) in order to visualize the assessments of the metrics of one attributte. And we have also the Radar visualization (https://github.com/dlumbrer/kbn_radar) in order to visualize projects (each project is an area of the radar) with their attribute assessment (each sommet is an attribute).

So, we need to have in ES the scores of the metrics (for the polar vis) and maybe a general score of each attribute (for the radar vis). The sommets and the height of the polar and radar vis are defined by a metric of ES, so we need to think how to retrieve the score using a metric of ES

**Comment by acs** [comment]
After the assessment a new index grimoirelab_scores is generated with the information about the scores. For example:

```
 {
        "_index": "grimoirelab_scores",
        "_type": "items",
        "_id": "S95uEmIB4g2k0UcN2xVK",
        "_score": 1,
        "_source": {
          "score": 2,
          "metric": "GitHubEnrich",
          "goal": "Product",
          "project": "perceval",
          "attribute": "Vitality"
        }
      }
```

@dlumbrer is that enough to start adding the assessment viz to our dashboards?

**Comment by acs** [comment]
RIght now we have the panel working for showing the assessment. So we just need to do the assessment when doing the viz, and to load the right panel.

**Comment by acs** [comment]
All done in: https://github.com/Bitergia/prosoul/pull/76

Now the assessment dashboard is added to kibana and to the menu.
